# Generated by Django 5.1.5 on 2025-01-24 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_post_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Description",
            new_name="description",
        ),
    ]
