# Generated by Django 5.1.5 on 2025-01-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_rename_description_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
