# Generated by Django 5.1.5 on 2025-01-26 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_post_user_post_author_post_date_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="authorName",
        ),
    ]
